export { Header } from './Header';
export type { HeaderProps } from './Header';
export { Footer } from './Footer';
export type { FooterProps } from './Footer';
export { Main } from './Main';
export type { MainProps } from './Main';
export { Root } from './Root';
export type { RootProps } from './Root';
export { Content } from './Content';
export type { ContentProps } from './Content';
export { Sider } from './Sider';
export type { SiderProps } from './Sider';
