declare const styles: {
  readonly 'rovna-ui-tag': string;
  readonly 'rovna-ui-tag-preset-blue': string;
  readonly 'rovna-ui-tag-preset-blue-light': string;
  readonly 'rovna-ui-tag-preset-cyan': string;
  readonly 'rovna-ui-tag-preset-cyan-light': string;
  readonly 'rovna-ui-tag-preset-default': string;
  readonly 'rovna-ui-tag-preset-geekblue': string;
  readonly 'rovna-ui-tag-preset-geekblue-light': string;
  readonly 'rovna-ui-tag-preset-gray': string;
  readonly 'rovna-ui-tag-preset-gray-light': string;
  readonly 'rovna-ui-tag-preset-green': string;
  readonly 'rovna-ui-tag-preset-green-light': string;
  readonly 'rovna-ui-tag-preset-purple': string;
  readonly 'rovna-ui-tag-preset-purple-light': string;
  readonly 'rovna-ui-tag-preset-red': string;
  readonly 'rovna-ui-tag-preset-red-light': string;
  readonly 'rovna-ui-tag-preset-volcano': string;
  readonly 'rovna-ui-tag-preset-volcano-light': string;
  readonly 'rovna-ui-tag-preset-yellow': string;
  readonly 'rovna-ui-tag-preset-yellow-light': string;
  readonly 'rovna-ui-tag-shape-ellipse': string;
  readonly 'rovna-ui-tag-shape-round': string;
  readonly 'rovna-ui-tag-size-large': string;
  readonly 'rovna-ui-tag-size-medium': string;
};
export = styles;
