export const SAMOLET_SERVICES = [
  's.pro',
  's.team',
  's.materials',
  's.progress',
  's.tender',
  's.smr',
  's.center',
  's.control',
  's.home',
  's.project',
  'roomer',
  's.kek',
  's.cost',
  's.volume',
  's.contracts',
  's.pass',
  's.docs',
  's.security',
  's.blueprint',
  's.fine',
  's.plan',
  's.task',
  's.limon',
  's.ecm',
  's.aed',
  's.info',
  's.act',
  's.cp',
  's.budget',
  's.viewer',
  'tableau',
  'tendata',
  's.record',
  's.reputation',
  's.oda',
  's.catalog',
  's.pass-report',
  's.mkpp',
  's.sign',
  's.warehouse',
] as const;

export type SamoletService = (typeof SAMOLET_SERVICES)[number];
