module.exports = {
  '\\.css$': 'identity-obj-proxy',

  '^antd-core/es/(.*)$': 'antd-core/lib/$1',
  '^@rovna-ui/icons/(.*)$': '<rootDir>/../tend-ui-icons/src/$1',
  '^@rovna-ui/hooks/(.*)$': '<rootDir>/../tend-ui-hooks/src/$1',
  '^@rovna-ui/primitives/(.*)$': '<rootDir>/../tend-ui-primitives/src/$1',
  '^@rovna-ui/filters/(.*)$': '<rootDir>/../tend-ui-filters/src/$1',
  '^@rovna-ui/typography/(.*)$': '<rootDir>/../tend-ui-typography/src/$1',
  '^@rovna-ui/base/(.*)$': '<rootDir>/../tend-ui-base/src/$1',
  '^@rovna-ui/form/(.*)$': '<rootDir>/../tend-ui-form/src/$1',

  '^@rovna-internal/components/(.*)$': '<rootDir>/../tend-ui/src/$1',
  '^@rovna-internal/primitives/(.*)$': '<rootDir>/../tend-ui-primitives/src/$1',
  '^@rovna-internal/fonts/(.*)$': '<rootDir>/../tend-ui-fonts/src/$1',
  '^@rovna-internal/logos/(.*)$': '<rootDir>/../tend-ui-logos/src/$1',
  '^@rovna-internal/styling/(.*)$': '<rootDir>/../tend-ui-styling/src/$1',
  '^@rovna-internal/tokens/(.*)$': '<rootDir>/../tend-ui-tokens/src/$1',
  '^@rovna-internal/utils/(.*)$': '<rootDir>/../tend-ui-utils/src/$1',
  '^@rovna-internal/locale/(.*)$': '<rootDir>/../tend-ui-locale/src/$1',
  '^@rovna-internal/hooks/(.*)$': '<rootDir>/../tend-ui-hooks/src/$1',
  '^@rovna-internal/types/(.*)$': '<rootDir>/../tend-ui-types/src/$1',
  '^@rovna-internal/factories/(.*)$': '<rootDir>/../tend-ui-factories/src/$1',
  '^@rovna-internal/api/(.*)$': '<rootDir>/../tend-ui-api/src/$1',
  '^@rovna-internal/theme/(.*)$': '<rootDir>/../tend-ui-theme/src/$1',
  '^@rovna-internal/icons/(.*)$': '<rootDir>/../tend-ui-icons/src/$1',
  '^@rovna-internal/grid/(.*)$': '<rootDir>/../tend-ui-grid/src/$1',
  '^@rovna-internal/typography/(.*)$': '<rootDir>/../tend-ui-typography/src/$1',
  '^@rovna-internal/header/(.*)$': '<rootDir>/../tend-ui-header/src/$1',
  '^@rovna-internal/tree/(.*)$': '<rootDir>/../tend-ui-tree/src/$1',
  '^@rovna-internal/table/(.*)$': '<rootDir>/../tend-ui-table/src/$1',
  '^@rovna-internal/filters/(.*)$': '<rootDir>/../tend-ui-filters/src/$1',
  '^@rovna-internal/columns-settings/(.*)$': '<rootDir>/../tend-ui-columns-settings/src/$1',
  '^@rovna-internal/base/(.*)$': '<rootDir>/../tend-ui-base/src/$1',
  '^@rovna-internal/upload/(.*)$': '<rootDir>/../tend-ui-upload/src/$1',
  '^@rovna-internal/form/(.*)$': '<rootDir>/../tend-ui-form/src/$1',
};
